### PR TITLE
Add MacOS Bundle Assets

### PR DESCRIPTION
**Pull request by CalmBit**
Still a work in progress, but it's coming along :)

Sorry about the non-atomicity of the gitignore change - I at the least committed it separately, but can reverse it if you'd like!

### CODE REVIEW

**Comment by nueh** [comment]
Sorry, but your .icns file comprises only one icon instead of ten in different sizes and in your Info.plist 
> ```xml
> <key>NSHighResolutionCapable</key>
> <true/>
> <key>NSSupportsAutomaticGraphicsSwitching</key>
> <true/>```
are missing.

[This](https://github.com/muesli/telephant/files/3202598/telephant.icns.zip) file contains all ten albeit automatically converted icons

**Comment by CalmBit** [comment]
Good job catching that! I don't use icns a lot, as you might have guessed ^^"

**Comment by muesli** [comment]
@CalmBit I wonder why I never merged this. Looks good to go? I guess I was just waiting for your OK since you mentioned it being a work-in-progress.

**Comment by CalmBit** [comment]
I'm not exactly sure either, apart from the fact that I was unsure about the format and still seeing how it worked. It should be fine though, thanks to @nueh 's contribution. I'd greenlight it!

**Pull request merged**
